version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: dgeta1111/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/cats/images/
  frontend:    
    image: dgeta1111/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: dgeta1111/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/static/media/cats/images/