services:
  backend:
    build: ./backend
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kittygram_net

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - kittygram_net

volumes:
  pg_data:
  static:
  media:

networks:
  kittygram_net:
    driver: bridge
