version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_net

  backend:
    image: dgeta1111/kittygram_backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - static:/backend_static/
      - media:/app/media/cats/images/
    networks:
      - kittygram_net

  frontend:    
    image: dgeta1111/kittygram_frontend
    env_file: .env
    command: sh -c "cp -r /app/build/. /static/ && nginx -g 'daemon off;'"
    volumes:
      - static:/static
    networks:
      - kittygram_net

  gateway:
    image: dgeta1111/kittygram_gateway
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - backend
    networks:
      - kittygram_net

networks:
  kittygram_net:
    driver: bridge
